name: Check

on:
  push:
    branches: [main, develop]
  pull_request:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Check
        run: deno task ok

      - name: Publish (Dry Run)
        run: deno publish --dry-run
