name: Check

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v5
      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Check
        run: deno task ok

      - name: Publish JSR (Dry Run)
        run: deno publish --dry-run

      - name: Publish npm (Dry Run)
        run: ./scripts/build_all.sh
