name: "Pull Request Labeler"
on:
  pull_request

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-slim
    steps:
      - uses: actions/labeler@v6
