name: Publish JSR

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 15

    permissions:
      contents: read
      # Need for publish
      id-token: write

    steps:
      - uses: actions/checkout@v5
      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Check
        run: deno task ok

      - name: Publish package
        run: deno publish
